parameters:
    winzou_cache.factory.class:         winzou\CacheBundle\CacheFactory

    winzou_cache.driver.apc_class:      winzou\CacheBundle\Cache\ApcCache
    winzou_cache.driver.array_class:    winzou\CacheBundle\Cache\ArrayCache
    winzou_cache.driver.file_class:     winzou\CacheBundle\Cache\FileCache
    winzou_cache.driver.memcache_class: winzou\CacheBundle\Cache\MemcacheCache
    winzou_cache.driver.xcache_class:   winzou\CacheBundle\Cache\XcacheCache
    winzou_cache.driver.zenddata_class: winzou\CacheBundle\Cache\ZendDataCache

services:
    winzou_cache.factory:
        class:     %winzou_cache.factory.class%
        arguments: [ {'cache_dir': %winzou_cache.options.cache_dir% } ]

    winzou_cache:
        factory_service: winzou_cache.factory
        factory_method:  get
        class:           %winzou_cache.internal.default_driver_class%
        arguments:
            - %winzou_cache.options.default_driver%

    winzou_cache.apc:
        class: %winzou_cache.driver.apc_class%

    winzou_cache.array:
        class: %winzou_cache.driver.array_class%

    winzou_cache.file:
        class: %winzou_cache.driver.file_class%
        arguments:
            - %winzou_cache.options.cache_dir%

    winzou_cache.memcache:
        class: %winzou_cache.driver.memcache_class%

    winzou_cache.xcache:
        class: %winzou_cache.driver.xcache_class%

    winzou_cache.zenddata:
        class: %winzou_cache.driver.zenddata_class%