parameters:
    winzou_cache.factory.class:         winzou\CacheBundle\CacheFactory
    winzou_cache.driver.abstract_class: winzou\CacheBundle\Cache\AbstractCache
    winzou_cache.driver.default:        File

services:
    winzou_cache.factory:
        class:     %winzou_cache.factory.class%
        arguments: [ {'cacheDir': %winzou_cache.options.cache_dir% } ]

    winzou_cache.cache:
        factory_service: winzou_cache.factory
        factory_method:  build
        class: winzou\CacheBundle\Cache\FileCache
        arguments:
            - %winzou_cache.driver.default%